server:
  port: 8080

ecommerceThreads: 10

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
